version: '3.8'

services:
  hoodini:
    image: pentamorfico/hoodini:latest
    pull_policy: always
    volumes:
      # Persist downloaded databases
      - hoodini-data:/app/src/hoodini/data
      # Mount current directory as working directory/output
      - .:/work
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  hoodini-data:
