name: hoodini
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pip
  - openssl
  - certifi
  - ca-certificates
  - pigz
  - blast
  - diamond
  - skani
  - fastani
  - padloc>=2.0.0
  - genomad
  - mafft
  - foldseek
  - famsa
  - veryfasttree
  - lightpanda
  - foldmason
  - defense-finder>=2.0.0

