name: hoodini
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pip
  - openssl
  - certifi
  - ca-certificates
  - entrez-direct
  - aria2
  - pigz
  - blast
  - diamond
  - skani
  - fastani
  - padloc>=2.0.0
  - genomad
  - mafft
  - foldseek
  - infernal
  - famsa
  - veryfasttree
  - firefox
  - gtk3
  - atk
  - xorg-libxcomposite
  - xorg-libxdamage
  - xorg-libxfixes
  - xorg-libxrandr
  - xorg-libxrender
  - xorg-libxext
  - cairo
  - pango
  - gdk-pixbuf
  - fontconfig
  - alsa-lib

