name: hoodini
channels:
  - bioconda
  - conda-forge
  - defaults
  - padlocbio
  - russel88
dependencies:
  - python>=3.8
  - pandas
  - numpy
  - matplotlib
  - rich
  - rich-click
  - pyarrow
  - polars
  - biopython
  - networkx
  - requests
  - tomli
  - ete3
  - diamond
  - skani
  - fastani
  - padloc>=2.0.0
  - genomad
  - mafft
  - foldseek
  - infernal
  - famsa
  - veryfasttree
  - openssl
  - certifi
  - ca-certificates
  - pip
  - entrez-direct
  - aria2
  - pigz
  - blast
  - cctyper
  - pip:
      - pyhmmer
      - diamondonpy
      - uniprot-id-mapper
      - alphafetcher
      - taxoniq
      - gb-io
      - orfipy
      - httpx
      - aiohttp
      - git+https://github.com/pentamorfico/CRISPRCasTyper.git@develop
      - aria2p
      - jinja2
      - mdmparis-defense-finder
      - mappy

