name: fastgcsnap
channels:
  - padlocbio
  - russel88
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - aria2
  - biopython>=1.81
  - cctyper>=1.8.0
  - dendropy>=4
  - diamond>=2
  - ete3>=3
  - famsa>=2
  - fasttree>=2
  - infernal>=1.1.4
  - ncbi-datasets-cli>=15.0.0
  - padloc>=1.1.0
  - pandas>=2.0
  - requests
  - taxonkit>=0.14.2
  - numpy>=1.2
  - pyarrow>=12.0
  - matplotlib
  - defense-finder>=1.0.9
  - rich
  - rich-click
