[project]
name = "hoodini"
version = "1.0.0"
description = "magic gene-neighborhood analyses"

[tool.pixi]
channels = ["conda-forge", "bioconda", "padlocbio", "russel88", "defaults"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[tool.pixi.dependencies]
python = ">=3.10"
pandas = "*"
numpy = "*"
matplotlib = "*"
rich = "*"
"rich-click" = "*"
pyarrow = "*"
polars = "*"
biopython = "*"
networkx = "*"
requests = "*"
tomli = "*"
ete3 = "*"
diamond = "*"
skani = "*"
fastani = "*"
padloc = ">=2.0.0"
genomad = "*"
mafft = "*"
foldseek = "*"
infernal = "*"
famsa = "*"
veryfasttree = "*"
openssl = "*"
certifi = "*"
"ca-certificates" = "*"
entrez-direct = "*"
aria2 = "*"
pigz = "*"
blast = "*"
cctyper = "*"

# PyPI (pip) dependencies
"pypi:pyhmmer" = "*"
"pypi:diamondonpy" = "*"
"pypi:uniprot-id-mapper" = "*"
"pypi:alphafetcher" = "*"
"pypi:taxoniq" = "*"
"pypi:gb-io" = "*"
"pypi:orfipy" = "*"
"pypi:httpx" = "*"
"pypi:aiohttp" = "*"
"pypi:aria2p" = "*"
"pypi:jinja2" = "*"
"pypi:mdmparis-defense-finder" = "*"
"pypi:mappy" = "*"
"pypi:CRISPRCasTyper" = { git = "https://github.com/pentamorfico/CRISPRCasTyper.git", rev = "develop" }

[tool.pixi.tasks]
# Quick run of the CLI
hoodini = "python -m hoodini --help"
