import subprocess
from io import StringIO
from pathlib import Path

import polars as pl

from hoodini.pipeline.helpers.jackhmmer_search import parallel_jackhmmer
from hoodini.pipeline.helpers.mmseqs_clustering import cluster_with_mmseqs
from hoodini.utils.logging_utils import info, warn
from hoodini.utils.polars_adapters import to_polars


def cluster_proteins(
    all_prots: pl.DataFrame | pl.DataFrame,
    output_dir: str | Path,
    clust_method: str = "deepmmseqs",
    sorfs: bool = False,
) -> pl.DataFrame:
    """
    Cluster neighbor proteins and annotate with fam_cluster.

    Expected Files:
    ---------------
    - all_prots: DataFrame with columns 'id', 'sequence', 'target_prot'
    - {output}/results.fasta (generated by parse_assemblies)

    Generated Files:
    ----------------
    - {output}/target_prots.fasta: Target proteins extracted for alignment
    - {output}/target_prots.aln: Multiple sequence alignment (if clust_method != 'none')
    - {output}/cluster_results.tsv (method-specific): Clustering output

    Process:
    --------
    1. Extracts target proteins from all_prots
    2. Runs clustering using specified method (deepmmseqs, diamond_deepclust, jackhmmer, or none)
    3. Assigns fam_cluster IDs to proteins based on clustering results
    4. Writes alignment file for phylogenetic analysis

    Parameters:
    -----------
    - all_prots: DataFrame with protein data
    - output_dir: path to output folder
    - clust_method: one of ['diamond_deepclust', 'deepmmseqs', 'jackhmmer', 'none']
    - sorfs: whether to filter based on sORF/orfipy rules

    Returns:
    --------
    pl.DataFrame with added 'fam_cluster' column (int or null)
    """
    if isinstance(all_prots, pl.DataFrame):
        all_prots = to_polars(all_prots)

    if all_prots.height == 0:
        warn("No proteins to cluster")
        return all_prots

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    faa_path = output_dir / "results.fasta"

    def write_fasta(df: pl.DataFrame, id_col: str, seq_col: str, path: Path) -> None:
        with open(path, "w") as fh:
            for row in df.select([id_col, seq_col]).iter_rows(named=True):
                fh.write(f">{row[id_col]}\n")
                seq = row[seq_col]
                for i in range(0, len(seq), 80):
                    fh.write(seq[i : i + 80] + "\n")

    fasta_df = all_prots.select(["id", "sequence"]).drop_nulls().unique(subset=["id"], keep="first")
    write_fasta(fasta_df, "id", "sequence", faa_path)

    if clust_method == "diamond_deepclust":
        cmd = ["diamond", "deepclust", "-d", faa_path, "--member-cover", "0.8"]
        result = subprocess.run(cmd, capture_output=True)
        if result.returncode != 0:
            stderr_msg = result.stderr.decode("utf-8", errors="replace").strip()
            stdout_msg = result.stdout.decode("utf-8", errors="replace").strip()
            raise RuntimeError(
                f"diamond deepclust failed (exit code {result.returncode}):\n"
                f"  Command: {' '.join(str(c) for c in cmd)}\n"
                f"  Stderr: {stderr_msg or '(empty)'}\n"
                f"  Stdout: {stdout_msg[:500] if stdout_msg else '(empty)'}"
            )
        clusterdf = pl.read_csv(
            StringIO(result.stdout.decode("utf-8")),
            separator="\t",
            has_header=False,
            new_columns=["clu_rep_seq", "member"],
        )

    elif clust_method == "deepmmseqs":
        tmp_dir = Path(output_dir) / "tmp_mmseqs"
        tmp_dir.mkdir(parents=True, exist_ok=True)
        output_file = Path(output_dir) / "deepmmseqs_results.tsv"
        cluster_with_mmseqs(
            faa_path,
            tmp_dir,
            max_steps=5,
            sensitivity=15,
            cluster_mode=1,
            cluster_steps=9,
            cov_mode=0,
            coverage=0.7,
            output=output_file,
        )
        clusterdf = pl.read_csv(
            output_file,
            separator="\t",
            has_header=False,
            new_columns=["clu_rep_seq", "member"],
        )

    elif clust_method == "jackhmmer":
        clusterdf = parallel_jackhmmer(faa_path)

    elif clust_method == "blastp":
        tmp_dir = Path(output_dir) / "tmp"
        tmp_dir.mkdir(parents=True, exist_ok=True)
        db_prefix = tmp_dir / "blastdb"
        subprocess.run(
            ["makeblastdb", "-in", faa_path, "-dbtype", "prot", "-out", str(db_prefix)], check=True
        )
        blast_out = tmp_dir / "blastp_results.tsv"
        cmd = [
            "blastp",
            "-query",
            faa_path,
            "-db",
            str(db_prefix),
            "-outfmt",
            "6 qseqid sseqid bitscore evalue pident length qcovs",
            "-out",
            str(blast_out),
        ]
        subprocess.run(cmd, check=True)
        df_blast = pl.read_csv(
            blast_out,
            separator="\t",
            has_header=False,
            new_columns=["qseqid", "sseqid", "bitscore", "evalue", "pident", "length", "qcovs"],
        )
        df_blast = df_blast[df_blast["qseqid"] != df_blast["sseqid"]]
        parent = {}

        def find(x):
            parent.setdefault(x, x)
            if parent[x] != x:
                parent[x] = find(parent[x])
            return parent[x]

        def union(x, y):
            rx, ry = find(x), find(y)
            if rx != ry:
                parent[ry] = rx

        ids = set(df_blast["qseqid"]).union(df_blast["sseqid"])
        for i in ids:
            parent[i] = i
        for row in df_blast.iter_rows(named=True):
            union(row["qseqid"], row["sseqid"])
        comps = {}
        for i in ids:
            r = find(i)
            comps.setdefault(r, []).append(i)
        records = []
        for members in comps.values():
            rep = sorted(members)[0]
            for m in members:
                records.append((rep, m))
        clusterdf = pl.DataFrame(records, columns=["clu_rep_seq", "member"])

    else:
        raise ValueError(f"Unsupported clustering method: {clust_method}")

    clusterdf_pl = to_polars(clusterdf)

    clusterdf_pl = clusterdf_pl.with_columns(
        pl.col("clu_rep_seq").count().over("clu_rep_seq").alias("clu_size")
    )

    rep_to_fam = (
        clusterdf_pl.filter(pl.col("clu_size") >= 2)
        .select(["clu_rep_seq", "clu_size"])
        .unique(subset=["clu_rep_seq"])
        .sort("clu_size", descending=True)
        .with_columns(pl.int_range(pl.len()).add(1).cast(pl.Int64).alias("fam_cluster"))
        .select(["clu_rep_seq", "fam_cluster"])
    )

    clusterdf_pl = clusterdf_pl.join(rep_to_fam, on="clu_rep_seq", how="left")

    if sorfs:
        clusterdf_pl = clusterdf_pl.filter(
            ~((pl.col("member").str.contains("sORF")) & (pl.col("fam_cluster").is_null()))
        )
        clusterdf_pl = clusterdf_pl.filter(
            ~(
                pl.col("fam_cluster").count().over("fam_cluster")
                == pl.col("member").str.contains("orfipy").sum().over("fam_cluster")
            )
        )

    result = all_prots.join(
        clusterdf_pl.select(["member", "fam_cluster"]), left_on="id", right_on="member", how="left"
    )

    if "member" in result.columns:
        result = result.drop("member")

    info("✔️\tProtein clustering complete")

    return result
