[AMRFinder]
tsv = "https://osf.io/3uz2j/files/osfstorage/65fb446e73e1fe0044507ddb"
hmm = "https://osf.io/3uz2j/files/osfstorage/65fb446e99b346003daa2aeb"

[CAZy]
tsv = "https://osf.io/3uz2j/files/osfstorage/648a122ac8611603302524b0"
hmm = "https://osf.io/3uz2j/files/osfstorage/648a122cc86116030e2523a9"

[COG]
tsv = "https://osf.io/3uz2j/files/osfstorage/647b966285df480865775723"
hmm = "https://osf.io/3uz2j/files/osfstorage/647b9799bf3d0f0941d87eb2"

[FOAM]
tsv = "https://osf.io/3uz2j/files/osfstorage/642cb9b5d9cfc341d5b3d0c0"

[GVDB]
tsv = "https://osf.io/3uz2j/files/osfstorage/65fb534299b3460049aa325a"
hmm = "https://osf.io/3uz2j/files/osfstorage/65fb534ed09d170038eee97d"

[KEGG]
tsv = "https://osf.io/3uz2j/files/osfstorage/642cb9ca919206359beef462"

[KOFam_all]
hmm = "https://osf.io/3uz2j/files/osfstorage/648a11d7bee36d02690e560a"

[KOFam_eukaryote]
hmm = "https://osf.io/3uz2j/files/osfstorage/64824200cb70be0156f97282"

[KOFam_prokaryote]
hmm = "https://osf.io/3uz2j/files/osfstorage/64823a35cb70be0160f96b18"

[NFixDB]
tsv = "https://osf.io/3uz2j/files/osfstorage/6764902c22304e1d7daf12c4"
hmm = "https://osf.io/3uz2j/files/osfstorage/67649030e6bd1d1feec55aff"

[Pfam]
tsv = "https://osf.io/3uz2j/files/osfstorage/65fb00afbafcc80124442241"
hmm = "https://osf.io/3uz2j/files/osfstorage/65fb00eb656446013ca7cb41"

[PGAP]
tsv = "https://osf.io/3uz2j/files/osfstorage/65fb4e8699b3460048aa2bea"
hmm = "https://osf.io/3uz2j/files/osfstorage/65fb4e9c99b346003daa3078"

[PHROG]
tsv = "https://osf.io/3uz2j/files/osfstorage/648a122f84f52c023bfe62fd"
hmm = "https://osf.io/3uz2j/files/osfstorage/648a123a84f52c0268fe66a5"

[PVOG]
tsv = "https://osf.io/3uz2j/files/osfstorage/65f350b98520371180880764"
hmm = "https://osf.io/3uz2j/files/osfstorage/65f350c1719c061189d49f30"

[TIGRFAM]
tsv = "https://osf.io/3uz2j/files/osfstorage/65fb32b773e1fe003150870b"
hmm = "https://osf.io/3uz2j/files/osfstorage/65fb32c1d09d17001deef05a"

[VOG]
tsv = "https://osf.io/3uz2j/files/osfstorage/648a123ddc523b02d9db4f7d"
hmm = "https://osf.io/3uz2j/files/osfstorage/648a123fc861160338252597"

[VOG-r225]
tsv = "https://osf.io/3uz2j/files/osfstorage/6704391b3be16c7b39a20607"
hmm = "https://osf.io/3uz2j/files/osfstorage/670439b08e178314a432d3c6"
